# NOTE: update this with your service name
service: serverless-todo

# serverless-webpack configuration
# Enable auto-packing of external modules
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${file(env.yml):dev}
  
functions:
  todos:
    handler: app/controller/todo.handler
    events:
      - http:
          path: /todos
          method: post
          cors: true
      - http:
          path: /todos
          method: put
          cors: true   
      - http:
          path: /todos
          method: get
          cors: true  
      - http:
          path: /todos
          method: delete
          cors: true                           